// Generated by gencpp from file turtlebot_stage/agentState.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_STAGE_MESSAGE_AGENTSTATE_H
#define TURTLEBOT_STAGE_MESSAGE_AGENTSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <nav_msgs/Odometry.h>

namespace turtlebot_stage
{
template <class ContainerAllocator>
struct agentState_
{
  typedef agentState_<ContainerAllocator> Type;

  agentState_()
    : agent_role(0)
    , uID(0)
    , odom()
    , degree(0)
    , isAP(0)  {
    }
  agentState_(const ContainerAllocator& _alloc)
    : agent_role(0)
    , uID(0)
    , odom(_alloc)
    , degree(0)
    , isAP(0)  {
    }



   typedef uint32_t _agent_role_type;
  _agent_role_type agent_role;

   typedef uint32_t _uID_type;
  _uID_type uID;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _odom_type;
  _odom_type odom;

   typedef uint32_t _degree_type;
  _degree_type degree;

   typedef uint32_t _isAP_type;
  _isAP_type isAP;




  typedef boost::shared_ptr< ::turtlebot_stage::agentState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_stage::agentState_<ContainerAllocator> const> ConstPtr;

}; // struct agentState_

typedef ::turtlebot_stage::agentState_<std::allocator<void> > agentState;

typedef boost::shared_ptr< ::turtlebot_stage::agentState > agentStatePtr;
typedef boost::shared_ptr< ::turtlebot_stage::agentState const> agentStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_stage::agentState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_stage::agentState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot_stage

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'turtlebot_stage': ['/home/exbot/catkin_ws_relay/src/turtlebot_stage/msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_stage::agentState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_stage::agentState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_stage::agentState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_stage::agentState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_stage::agentState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_stage::agentState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_stage::agentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2aad78d9b6be9facf3d860a8a1c79738";
  }

  static const char* value(const ::turtlebot_stage::agentState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2aad78d9b6be9facULL;
  static const uint64_t static_value2 = 0xf3d860a8a1c79738ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_stage::agentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_stage/agentState";
  }

  static const char* value(const ::turtlebot_stage::agentState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_stage::agentState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 agent_role\n\
uint32 uID\n\
nav_msgs/Odometry odom\n\
uint32 degree\n\
uint32 isAP\n\
\n\
================================================================================\n\
MSG: nav_msgs/Odometry\n\
# This represents an estimate of a position and velocity in free space.  \n\
# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n\
# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n\
Header header\n\
string child_frame_id\n\
geometry_msgs/PoseWithCovariance pose\n\
geometry_msgs/TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseWithCovariance\n\
# This represents a pose in free space with uncertainty.\n\
\n\
Pose pose\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertainty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::turtlebot_stage::agentState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_stage::agentState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agent_role);
      stream.next(m.uID);
      stream.next(m.odom);
      stream.next(m.degree);
      stream.next(m.isAP);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct agentState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_stage::agentState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot_stage::agentState_<ContainerAllocator>& v)
  {
    s << indent << "agent_role: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.agent_role);
    s << indent << "uID: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.uID);
    s << indent << "odom: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.odom);
    s << indent << "degree: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.degree);
    s << indent << "isAP: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.isAP);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_STAGE_MESSAGE_AGENTSTATE_H
